### ISSUE TITLE
IR LED Pin Distance to the AC

### ISSUE THREAD

**Issue by nazmibojan** [megabitsenmzq/ESP32-HomeKit-Remote#1]
Hi @megabitsenmzq ,

I just curious if you were using external IR LED, how long the distance between your device to the AC?

Thanks,
Nazm

**Comment by megabitsenmzq** [comment]
Yep，here is a photo.

![image](https://github.com/user-attachments/assets/165898bc-b1ed-4edc-b997-3dae5bf2dedb)

**Comment by nazmibojan** [comment]
is it possible to put that IR LED and device in the table 2m away maybe from the AC @megabitsenmzq ?

**Comment by megabitsenmzq** [comment]
I didn’t try that. If it does not work from 2m away, maybe you can drive the LED with a transistor instead of driving from the IO PIN directly.

**Comment by nazmibojan** [comment]
What do you mean translator @megabitsenmzq ? Is it [IRTranslator](https://github.com/mattcuk/IRtranslator) library? How can it make my remotr distance longer?

**Comment by megabitsenmzq** [comment]
Sorry about the typo. I overlooked that. I mean transistor, or maybe mosfet.

**Comment by nazmibojan** [comment]
I see, we can use transistor to make switching for bigger IR input voltage ya.
Thanks for your insight @megabitsenmzq
